### ISSUE TITLE
Cannot update NuGet packages

### ISSUE THREAD

**Issue by stevenmgregory** [BuildingsLabs/SmartConnectorSamples#1]
When I build the solution in VS2015 I get the error message saying that there is a directive or assembly  missing. When I try to update the NuGet packages, I get the 'unable to find package' error - see attached screen shots:

![nugeterror](https://cloud.githubusercontent.com/assets/20467975/22001801/7f9c95de-dc9b-11e6-99ad-a0f1309bad50.PNG)
![compile error](https://cloud.githubusercontent.com/assets/20467975/22001874/d4f5b11e-dc9b-11e6-8ee3-d5d7e0e5b3b2.PNG)

**Comment by DarthStem** [comment]
master branch updated with updated NuGet references.
